apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-calculator-pipeline-run
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: git-url
      value: https://github.com/SabaShahzadi90/tax-calculator
    - name: image-url
      value: us.icr.io/juphc-namespace/tax-calculator:latest
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-workspace-pvc
